test: &default

  # Credentials for REST APIs
  client_id: AebgsR9esD-60D_J03TQBjefHmH5o2gYHTwBZ9vsKmU2uBc8RBxIS_SRIeMY4ybV8Qct2M9bA3Ecegaa
  client_secret: EJDTkwi_jaycNQJ_DnGiG2MKottDqP8oK2N3_qru_rpJ-N2_2nl5WOkxHLhu0uuI-OB_sloqVCefbOWq

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: gustavoelizalde@icloud.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
